//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gatelog
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int VehicleTypeId { get; set; }
        public string PlateNumber { get; set; }
        public int PurposeId { get; set; }
        public int ItemsToDeclareID { get; set; }
        public int VistiorTypeId { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ItemsToDeclare ItemsToDeclare { get; set; }
        public virtual PurposeOfVisit PurposeOfVisit { get; set; }
        public virtual User User { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
