//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gatelog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vtdi_gatelogdbEntities : DbContext
    {
        public vtdi_gatelogdbEntities()
            : base("name=vtdi_gatelogdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GateLog> GateLogs { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ItemsToDeclare> ItemsToDeclares { get; set; }
        public virtual DbSet<PurposeOfVisit> PurposeOfVisits { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
